const ABILITY_LABELS_PT: Record<string, string> = {
  adaptability: "Adaptabilidade",
  aftermath: "Efeito Residual",
  "air-lock": "Tranca de Ar",
  analytic: "Analítico",
  "anger-point": "Ponto de Fúria",
  "anger-shell": "Concha da Fúria",
  anticipation: "Antecipação",
  "arena-trap": "Armadilha de Arena",
  "armor-tail": "Cauda Blindada",
  "aroma-veil": "Véu Aromático",
  "aura-break": "Quebra de Aura",
  "bad-dreams": "Pesadelo",
  "ball-fetch": "Busca-bolas",
  battery: "Bateria",
  "battle-armor": "Armadura de Batalha",
  "beads-of-ruin": "Contas da Ruína",
  "beast-boost": "Impulso Bestial",
  berserk: "Furioso",
  "big-pecks": "Peito Estufado",
  blaze: "Labareda",
  bulletproof: "À Prova de Balas",
  "cheek-pouch": "Bochecha Recheada",
  "chilling-neigh": "Relincho Gélido",
  chlorophyll: "Clorofila",
  "clear-body": "Corpo Limpo",
  "cloud-nine": "Nona Nuvem",
  "color-change": "Muda de Cor",
  comatose: "Comatoso",
  commander: "Comandante",
  competitive: "Competitivo",
  "compound-eyes": "Olhos Compostos",
  contrary: "Inverso",
  corrosion: "Corrosão",
  costar: "Coestrela",
  "cotton-down": "Algodão Solto",
  "cud-chew": "Ruminação",
  "cursed-body": "Corpo Amaldiçoado",
  "cute-charm": "Charme Fofo",
  damp: "Umidade",
  dancer: "Dançarino",
  "dark-aura": "Aura Sinistra",
  "dauntless-shield": "Escudo Destemido",
  dazzling: "Deslumbrante",
  defeatist: "Derrotista",
  defiant: "Desafiador",
  disguise: "Disfarce",
  download: "Download",
  "dragons-maw": "Mandíbula de Dragão",
  drizzle: "Chuvisco",
  drought: "Seca",
  "dry-skin": "Pele Seca",
  "early-bird": "Madrugador",
  "earth-eater": "Devorador de Terra",
  "effect-spore": "Esporo Ativo",
  "electric-surge": "Onda Elétrica",
  electromorphosis: "Eletromorfose",
  "emergency-exit": "Saída de Emergência",
  "fairy-aura": "Aura Feérica",
  filter: "Filtro",
  "flame-body": "Corpo Flamejante",
  "flare-boost": "Impulso Flamejante",
  "flash-fire": "Absorve Fogo",
  "flower-gift": "Dádiva Floral",
  "flower-veil": "Véu Floral",
  fluffy: "Fofinho",
  forecast: "Previsão",
  forewarn: "Pressentimento",
  "friend-guard": "Guarda Amiga",
  frisk: "Vasculhar",
  "full-metal-body": "Corpo Metálico Total",
  "fur-coat": "Casaco de Pelos",
  "gale-wings": "Asas do Vento",
  gluttony: "Gula",
  "good-as-gold": "Vale Tanto Quanto Ouro",
  gooey: "Pegajoso",
  "grass-pelt": "Pelagem de Grama",
  "grassy-surge": "Onda Grama",
  "grim-neigh": "Relincho Sinistro",
  "guard-dog": "Cão de Guarda",
  "gulp-missile": "Míssil Engolido",
  guts: "Determinação",
  "hadron-engine": "Motor de Hádrons",
  harvest: "Colheita",
  healer: "Curador",
  heatproof: "Resistente ao Calor",
  "heavy-metal": "Metal Pesado",
  "honey-gather": "Coletor de Mel",
  hospitality: "Hospitalidade",
  "huge-power": "Força Bruta",
  "hunger-switch": "Troca por Fome",
  hustle: "Empenho",
  hydration: "Hidratação",
  "hyper-cutter": "Hiper Corte",
  "ice-body": "Corpo de Gelo",
  "ice-face": "Rosto de Gelo",
  "ice-scales": "Escamas de Gelo",
  illuminate: "Iluminar",
  illusion: "Ilusão",
  immunity: "Imunidade",
  imposter: "Impostor",
  infiltrator: "Infiltrador",
  "innards-out": "Vísceras Pra Fora",
  "inner-focus": "Foco Interior",
  insomnia: "Insônia",
  intimidate: "Intimidação",
  "intrepid-sword": "Espada Intrépida",
  "iron-barbs": "Espinhos de Ferro",
  "iron-fist": "Punho de Ferro",
  justified: "Justiceiro",
  "keen-eye": "Olho Aguçado",
  klutz: "Desajeitado",
  "leaf-guard": "Guarda Foliar",
  levitate: "Levitação",
  libero: "Líbero",
  "light-metal": "Metal Leve",
  "lightning-rod": "Para-raios",
  limber: "Flexibilidade",
  "lingering-aroma": "Aroma Persistente",
  "liquid-ooze": "Lodo Líquido",
  "liquid-voice": "Voz Líquida",
  "long-reach": "Longo Alcance",
  "magic-bounce": "Reflexo Mágico",
  "magic-guard": "Guarda Mágica",
  magician: "Mágico",
  "magma-armor": "Armadura de Magma",
  "magnet-pull": "Atração Magnética",
  "marvel-scale": "Escama Maravilha",
  "mega-launcher": "Mega Lançador",
  merciless: "Impiedoso",
  minus: "Menos",
  "mirror-armor": "Armadura Espelhada",
  "misty-surge": "Onda Nebulosa",
  "mold-breaker": "Quebra-molde",
  moody: "Instável",
  "motor-drive": "Motor Elétrico",
  moxie: "Confiança",
  multiscale: "Multiescama",
  multitype: "Multitipo",
  mummy: "Múmia",
  "mycelium-might": "Poder do Micélio",
  "natural-cure": "Cura Natural",
  "neutralizing-gas": "Gás Neutralizante",
  "no-guard": "Sem Guarda",
  normalize: "Normalizar",
  oblivious: "Distraído",
  opportunist: "Oportunista",
  "orichalcum-pulse": "Pulso de Oricalco",
  overcoat: "Sobretudo",
  overgrow: "Crescimento",
  "own-tempo": "Ritmo Próprio",
  "perish-body": "Corpo Mortal",
  pickpocket: "Punguista",
  pickup: "Catador",
  pixilate: "Fadificar",
  plus: "Mais",
  "poison-heal": "Cura Venenosa",
  "poison-point": "Ponto Venenoso",
  "poison-puppeteer": "Marionetista Venenoso",
  "poison-touch": "Toque Venenoso",
  "power-spot": "Ponto de Poder",
  prankster: "Brincalhão",
  pressure: "Pressão",
  "prism-armor": "Armadura Prisma",
  "propeller-tail": "Cauda de Hélice",
  protean: "Proteano",
  protosynthesis: "Protossíntese",
  "psychic-surge": "Onda Psíquica",
  "punk-rock": "Punk Rock",
  "pure-power": "Poder Puro",
  "purifying-salt": "Sal Purificador",
  "quark-drive": "Impulso Quark",
  "queenly-majesty": "Majestade Real",
  "quick-feet": "Pés Rápidos",
  "rain-dish": "Prato de Chuva",
  rattled: "Assustado",
  receiver: "Receptor",
  reckless: "Imprudente",
  refrigerate: "Refrigerar",
  regenerator: "Regenerador",
  ripen: "Maturar",
  rivalry: "Rivalidade",
  "rks-system": "Sistema RKS",
  "rock-head": "Cabeça de Pedra",
  "rocky-payload": "Carga de Pedras",
  "rough-skin": "Pele Áspera",
  "run-away": "Fuga",
  "sand-force": "Força da Areia",
  "sand-rush": "Pressa na Areia",
  "sand-spit": "Cuspe de Areia",
  "sand-stream": "Corrente de Areia",
  "sand-veil": "Véu de Areia",
  "sap-sipper": "Sorvedor de Seiva",
  schooling: "Cardume",
  scrappy: "Destemido",
  "screen-cleaner": "Limpa-telas",
  "seed-sower": "Semeador",
  "serene-grace": "Graça Serena",
  "shadow-shield": "Escudo Sombrio",
  "shadow-tag": "Marca Sombria",
  sharpness: "Afiação",
  "shed-skin": "Troca de Pele",
  "sheer-force": "Força Pura",
  "shell-armor": "Armadura de Concha",
  "shield-dust": "Pó Escudo",
  "shields-down": "Escudo Baixo",
  simple: "Simples",
  "skill-link": "Combo Perfeito",
  "slow-start": "Início Lento",
  "slush-rush": "Pressa na Neve",
  sniper: "Franco-atirador",
  "snow-cloak": "Manto de Neve",
  "snow-warning": "Aviso de Neve",
  "solar-power": "Energia Solar",
  "solid-rock": "Rocha Sólida",
  "soul-heart": "Coração de Alma",
  soundproof: "Antissom",
  "speed-boost": "Aceleração",
  stakeout: "Vigilância",
  stall: "Retardo",
  stalwart: "Inabalável",
  stamina: "Resistência",
  "stance-change": "Troca de Postura",
  static: "Estática",
  steadfast: "Firmeza",
  "steam-engine": "Motor a Vapor",
  steelworker: "Forjador de Aço",
  "steely-spirit": "Espírito de Aço",
  stench: "Fedor",
  "sticky-hold": "Aderência",
  "storm-drain": "Dreno de Tempestade",
  "strong-jaw": "Mandíbula Forte",
  sturdy: "Robustez",
  "suction-cups": "Ventosas",
  "super-luck": "Super Sorte",
  "supersweet-syrup": "Xarope Superdoce",
  "supreme-overlord": "Senhor Supremo",
  swarm: "Enxame",
  "sweet-veil": "Véu Doce",
  "swift-swim": "Nado Rápido",
  "sword-of-ruin": "Espada da Ruína",
  symbiosis: "Simbiose",
  synchronize: "Sincronia",
  "tablets-of-ruin": "Tábuas da Ruína",
  "tangled-feet": "Pés Trançados",
  technician: "Técnico",
  telepathy: "Telepatia",
  "tera-shift": "Mudança Tera",
  teravolt: "Teravolt",
  "thermal-exchange": "Troca Térmica",
  "thick-fat": "Gordura",
  "tinted-lens": "Lente Tingida",
  torrent: "Torrente",
  "tough-claws": "Garras Resistentes",
  "toxic-boost": "Impulso Tóxico",
  "toxic-chain": "Corrente Tóxica",
  "toxic-debris": "Detrito Tóxico",
  trace: "Cópia",
  transistor: "Transistor",
  triage: "Triagem",
  truant: "Vadiagem",
  turboblaze: "Turboflama",
  unaware: "Despercebido",
  unburden: "Aliviado",
  unnerve: "Nervosismo",
  "unseen-fist": "Punho Invisível",
  "vessel-of-ruin": "Recipiente da Ruína",
  "victory-star": "Estrela da Vitória",
  "vital-spirit": "Espírito Vital",
  "volt-absorb": "Absorve Eletricidade",
  "wandering-spirit": "Espírito Errante",
  "water-absorb": "Absorve Água",
  "water-bubble": "Bolha de Água",
  "water-compaction": "Compactação Aquática",
  "water-veil": "Véu de Água",
  "weak-armor": "Armadura Frágil",
  "well-baked-body": "Corpo Bem Assado",
  "white-smoke": "Fumaça Branca",
  "wimp-out": "Covardia",
  "wind-power": "Energia Eólica",
  "wind-rider": "Cavaleiro do Vento",
  "wonder-guard": "Guarda Maravilha",
  "wonder-skin": "Pele Maravilha",
  "zen-mode": "Modo Zen",
  "zero-to-hero": "Do Zero ao Herói",
};

function fallbackLabel(name: string): string {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function getAbilityLabelPt(name: string): string {
  return ABILITY_LABELS_PT[name] ?? fallbackLabel(name);
}
