// Nomes de golpes em português (a PokéAPI não fornece PT).
// O que não estiver aqui cai no fallback formatado.
export const MOVE_LABELS_PT: Record<string, string> = {
  // ----- Normal -----
  pound: "Pancada",
  "karate-chop": "Golpe de Karatê",
  "double-slap": "Tapa Duplo",
  "comet-punch": "Soco Cometa",
  "mega-punch": "Megasoco",
  "fire-punch": "Soco de Fogo",
  "ice-punch": "Soco de Gelo",
  "thunder-punch": "Soco do Trovão",
  scratch: "Arranhão",
  "vice-grip": "Torniquete",
  "guillotine": "Guilhotina",
  cut: "Cortar",
  "fury-attack": "Ataque Furioso",
  "horn-drill": "Broca de Chifre",
  "horn-attack": "Chifrada",
  tackle: "Investida",
  "body-slam": "Corpada",
  wrap: "Enrolar",
  "take-down": "Derrubada",
  thrash: "Surra",
  "double-edge": "Fio Duplo",
  "tail-whip": "Chicotada de Cauda",
  leer: "Encarar",
  growl: "Rosnar",
  roar: "Rugido",
  sing: "Cantar",
  supersonic: "Supersônico",
  "sonic-boom": "Estrondo Sônico",
  disable: "Desabilitar",
  "quick-attack": "Ataque Rápido",
  rage: "Fúria",
  "screech": "Guincho",
  "double-team": "Equipe Dupla",
  "harden": "Endurecer",
  "mega-kick": "Megachute",
  "jump-kick": "Chute Saltador",
  "rolling-kick": "Chute Giratório",
  headbutt: "Cabeçada",
  "horn-leech": "Chifre Sugador",
  strength: "Força",
  slam: "Pancadão",
  stomp: "Pisão",
  "constrict": "Constringir",
  "swords-dance": "Dança das Espadas",
  "cut-": "Cortar",
  "focus-energy": "Foco de Energia",
  bide: "Aguentar",
  "self-destruct": "Autodestruição",
  "egg-bomb": "Bomba-Ovo",
  lick: "Lambida",
  "smokescreen": "Cortina de Fumaça",
  "defense-curl": "Defesa Enrolada",
  "barrier": "Barreira",
  "light-screen": "Tela de Luz",
  haze: "Névoa",
  reflect: "Refletir",
  "focus-punch": "Soco Focado",
  "hyper-fang": "Hiperpresa",
  "super-fang": "Superpresa",
  slash: "Talho",
  substitute: "Substituto",
  "hyper-beam": "Hiper-Raio",
  "giga-impact": "Giga Impacto",
  recover: "Recuperar",
  "soft-boiled": "Cozido Leve",
  rest: "Descansar",
  "skull-bash": "Crânio na Marra",
  "spike-cannon": "Canhão de Espinhos",
  "fury-swipes": "Golpes Furiosos",
  agility: "Agilidade",
  transform: "Transformar",
  "tri-attack": "Tri-Ataque",
  "scary-face": "Cara Assustadora",
  swift: "Veloz",
  flail: "Sacudida",
  "rapid-spin": "Giro Rápido",
  "endeavor": "Empenho",
  facade: "Fachada",
  "extreme-speed": "Velocidade Extrema",
  "hyper-voice": "Hipervoz",
  "last-resort": "Último Recurso",
  protect: "Proteger",
  endure: "Resistir",
  "belly-drum": "Tambor de Barriga",
  "perish-song": "Canção Fatal",
  "mean-look": "Olhar Ameaçador",
  "metronome": "Metrônomo",
  "mimic": "Imitar",
  splash: "Espirro d'Água",
  "false-swipe": "Golpe Falso",
  "helping-hand": "Mãos à Obra",
  "play-rough": "Brincadeira Bruta",
  "wish": "Desejo",
  "boomburst": "Estrondo",
  "hidden-power": "Poder Oculto",
  "return": "Retribuir",

  // ----- Fire -----
  ember: "Brasa",
  flamethrower: "Lança-Chamas",
  "fire-spin": "Redemoinho de Fogo",
  "fire-blast": "Explosão de Fogo",
  "fire-fang": "Presa de Fogo",
  "flame-wheel": "Roda Flamejante",
  "flame-charge": "Carga Flamejante",
  "flare-blitz": "Investida Flamejante",
  "heat-wave": "Onda de Calor",
  "will-o-wisp": "Fogo-Fátuo",
  "fire-pledge": "Juramento de Fogo",
  overheat: "Superaquecer",
  "blaze-kick": "Chute Flamejante",
  "lava-plume": "Pluma de Lava",
  "fire-punch-": "Soco de Fogo",
  "sunny-day": "Dia Ensolarado",
  inferno: "Inferno",
  "fiery-dance": "Dança Ardente",
   "flame-burst": "Rajada de Fogo",

  // ----- Water -----
  "water-gun": "Jato d'Água",
  bubble: "Bolha",
  "bubble-beam": "Raio de Bolhas",
  "hydro-pump": "Hidrobomba",
  surf: "Surfar",
  "ice-beam": "Raio de Gelo",
  "aurora-beam": "Raio Aurora",
  waterfall: "Cachoeira",
  clamp: "Mordaça",
  withdraw: "Recolher",
  "water-pulse": "Pulso d'Água",
  "aqua-tail": "Cauda Aquática",
  "aqua-jet": "Jato Aquático",
  "water-pledge": "Juramento d'Água",
  "muddy-water": "Água Lamacenta",
  "rain-dance": "Dança da Chuva",
  "hydro-cannon": "Hidrocanhão",
  brine: "Salmoura",
  "water-spout": "Esguicho d'Água",
  scald: "Escaldar",
  "razor-shell": "Concha Navalha",
  "liquidation": "Liquidação",
  whirlpool: "Redemoinho",
  octazooka: "Octabazuca",

  // ----- Electric -----
  "thunder-shock": "Choque do Trovão",
  thunderbolt: "Raio",
  "thunder-wave": "Onda de Choque",
  thunder: "Trovão",
  "thunder-punch-": "Soco do Trovão",
  "thunder-fang": "Presa do Trovão",
  spark: "Faísca",
  discharge: "Descarga",
  "volt-tackle": "Investida de Volts",
  "charge-beam": "Raio Carregado",
  "wild-charge": "Carga Selvagem",
  "volt-switch": "Troca de Volts",
  "electro-ball": "Bola Elétrica",
  "nuzzle": "Esfregar",
  "shock-wave": "Onda de Choque",
  "zap-cannon": "Canhão Elétrico",

  // ----- Grass -----
  absorb: "Absorver",
  "mega-drain": "Megadreno",
  "leech-seed": "Semente Sanguessuga",
  "razor-leaf": "Folha Navalha",
  "vine-whip": "Chicote de Cipó",
  "solar-beam": "Raio Solar",
  "poison-powder": "Pó Venenoso",
  "stun-spore": "Esporo Atordoante",
  "sleep-powder": "Pó do Sono",
  "petal-dance": "Dança das Pétalas",
  "petal-blizzard": "Nevasca de Pétalas",
  "giga-drain": "Gigadreno",
  "seed-bomb": "Bomba de Sementes",
  "energy-ball": "Bola de Energia",
  "leaf-blade": "Lâmina de Folha",
  "leaf-storm": "Tempestade de Folhas",
  "magical-leaf": "Folha Mágica",
  synthesis: "Síntese",
  "grass-knot": "Nó de Grama",
  "wood-hammer": "Martelo de Madeira",
  "bullet-seed": "Sementes-Bala",
  "needle-arm": "Braço de Agulhas",
  "frenzy-plant": "Planta Frenética",
  "worry-seed": "Semente da Aflição",
  spore: "Esporo",

  // ----- Ice -----
  "ice-punch-": "Soco de Gelo",
  "powder-snow": "Pó de Neve",
  mist: "Neblina",
  blizzard: "Nevasca",
  haze_ice: "Névoa Gelada",
  "icy-wind": "Vento Gélido",
  "ice-fang": "Presa de Gelo",
  "ice-shard": "Estilhaço de Gelo",
  "icicle-spear": "Lança de Gelo",
  "icicle-crash": "Queda de Gelo",
  "frost-breath": "Sopro Gélido",
  "ice-ball": "Bola de Gelo",
  "freeze-dry": "Liofilizar",
  hail: "Granizo",
  "sheer-cold": "Frio Cortante",
  "aurora-veil": "Véu Aurora",

  // ----- Fighting -----
  "low-kick": "Chute Baixo",
  "double-kick": "Chute Duplo",
  submission: "Submissão",
  "seismic-toss": "Arremesso Sísmico",
  "brick-break": "Quebra-Tijolo",
  counter: "Contra-Ataque",
  "cross-chop": "Golpe Cruzado",
  "dynamic-punch": "Soco Dinâmico",
  "mach-punch": "Soco Veloz",
  "close-combat": "Combate Direto",
  "vital-throw": "Arremesso Vital",
  revenge: "Vingança",
  reversal: "Reviravolta",
  "rock-smash": "Esmaga-Pedra",
  "force-palm": "Palma de Força",
  "drain-punch": "Soco Sugador",
  "bulk-up": "Reforçar",
  detect: "Detectar",
  "aura-sphere": "Esfera de Aura",
  "focus-blast": "Explosão Focada",
  "sky-uppercut": "Gancho Celeste",
  "superpower": "Superpoder",
  "hammer-arm": "Braço-Martelo",
  "power-up-punch": "Soco Reforçado",

  // ----- Poison -----
  "poison-sting": "Ferroada Venenosa",
  acid: "Ácido",
  "sludge": "Lodo",
  "sludge-bomb": "Bomba de Lodo",
  "sludge-wave": "Onda de Lodo",
  smog: "Fumaça Tóxica",
  "poison-gas": "Gás Venenoso",
  toxic: "Tóxico",
  "poison-jab": "Picada Venenosa",
  "poison-fang": "Presa Venenosa",
  "poison-tail": "Cauda Venenosa",
  venoshock: "Choque Venenoso",
  "acid-spray": "Jato de Ácido",
  "cross-poison": "Veneno Cruzado",
  "gunk-shot": "Tiro de Sujeira",
  "toxic-spikes": "Espinhos Tóxicos",
  "clear-smog": "Névoa Limpa",
  "venom-drench": "Banho de Veneno",

  // ----- Ground -----
  "sand-attack": "Ataque de Areia",
  dig: "Cavar",
  earthquake: "Terremoto",
  fissure: "Fenda",
  "bone-club": "Clava de Osso",
  bonemerang: "Bumerangue de Osso",
  "bone-rush": "Saraivada de Ossos",
  magnitude: "Magnitude",
  "mud-slap": "Tapa de Lama",
  "mud-shot": "Tiro de Lama",
  "mud-bomb": "Bomba de Lama",
  "earth-power": "Poder da Terra",
  "sand-tomb": "Tumba de Areia",
  "drill-run": "Broca Perfurante",
  "high-horsepower": "Cavalos de Força",
  "sandstorm": "Tempestade de Areia",
  spikes: "Espinhos",

  // ----- Flying -----
  gust: "Rajada",
  "wing-attack": "Ataque de Asa",
  fly: "Voar",
  peck: "Bicada",
  "drill-peck": "Broca de Bico",
  "aerial-ace": "Ás dos Ares",
  "air-slash": "Corte de Ar",
  "air-cutter": "Lâmina de Vento",
  "sky-attack": "Ataque Celeste",
  hurricane: "Furacão",
  "brave-bird": "Pássaro Bravo",
  bounce: "Pular",
  pluck: "Beliscar",
  roost: "Pousar",
  tailwind: "Vento de Cauda",
  "feather-dance": "Dança das Penas",
  "dual-wingbeat": "Batida Dupla de Asas",
  "defog": "Dissipar",

  // ----- Psychic -----
  confusion: "Confusão",
  psychic: "Psíquico",
  psybeam: "Psicorraio",
  hypnosis: "Hipnose",
  meditate: "Meditar",
  "calm-mind": "Mente Calma",
  "dream-eater": "Devorador de Sonhos",
  "psycho-cut": "Psicocorte",
  "zen-headbutt": "Cabeçada Zen",
  "future-sight": "Visão do Futuro",
  "cosmic-power": "Poder Cósmico",
  "psyshock": "Psicochoque",
  "stored-power": "Poder Armazenado",
  teleport: "Teletransporte",
  "light-screen-": "Tela de Luz",
  "extrasensory": "Extrassensorial",
  "psychic-fangs": "Presas Psíquicas",
  "amnesia": "Amnésia",
  "miracle-eye": "Olho Milagroso",
  "magic-coat": "Manto Mágico",
  "power-swap": "Troca de Poder",

  // ----- Bug -----
  "string-shot": "Tiro de Teia",
  "leech-life": "Vida Sugadora",
  "pin-missile": "Míssil de Agulhas",
  twineedle: "Agulha Dupla",
  "bug-bite": "Mordida de Inseto",
  "signal-beam": "Raio Sinalizador",
  "x-scissor": "Tesoura-X",
  "bug-buzz": "Zumbido",
  "fury-cutter": "Cortador Furioso",
  megahorn: "Megachifre",
  "u-turn": "Retorno",
  "silver-wind": "Vento Prateado",
  "struggle-bug": "Inseto Lutador",
  "fell-stinger": "Ferrão Mortal",
  "first-impression": "Primeira Impressão",

  // ----- Rock -----
  "rock-throw": "Lançamento de Pedra",
  "rock-slide": "Deslizamento de Rochas",
  "rock-tomb": "Tumba de Rochas",
  "rock-blast": "Explosão de Rochas",
  "stone-edge": "Borda de Pedra",
  rollout: "Rolar",
  "ancient-power": "Poder Ancião",
  "power-gem": "Joia de Poder",
  "smack-down": "Derrubada de Pedra",
  "head-smash": "Cabeçada Brutal",
  "stealth-rock": "Pedras Ocultas",
  "rock-polish": "Polimento de Rocha",
  sandstorm_rock: "Tempestade de Areia",

  // ----- Ghost -----
  "night-shade": "Sombra Noturna",
  "confuse-ray": "Raio Confusor",
  "shadow-ball": "Bola Sombria",
  "shadow-punch": "Soco Sombrio",
  "shadow-claw": "Garra Sombria",
  "shadow-sneak": "Esgueirada Sombria",
  hex: "Maldição Menor",
  spite: "Rancor",
  grudge: "Ressentimento",
  nightmare: "Pesadelo",
  curse: "Maldição",
  "destiny-bond": "Laço do Destino",
  "phantom-force": "Força Fantasma",
  "ominous-wind": "Vento Sinistro",
  "astonish": "Espanto",
  "will-o-wisp-": "Fogo-Fátuo",

  // ----- Dragon -----
  "dragon-rage": "Fúria do Dragão",
  "dragon-breath": "Sopro do Dragão",
  "dragon-claw": "Garra do Dragão",
  "dragon-dance": "Dança do Dragão",
  "dragon-pulse": "Pulso do Dragão",
  "dragon-rush": "Investida do Dragão",
  "dragon-tail": "Cauda do Dragão",
  outrage: "Fúria",
  twister: "Tornado",
  "draco-meteor": "Meteoro Dragão",
  "spacial-rend": "Fenda Espacial",
  "roar-of-time": "Rugido do Tempo",
  "dual-chop": "Golpe Duplo",
  "scale-shot": "Tiro de Escamas",

  // ----- Dark -----
  bite: "Mordida",
  crunch: "Mastigada",
  "faint-attack": "Ataque Furtivo",
  "feint-attack": "Ataque Furtivo",
  pursuit: "Perseguição",
  "knock-off": "Nocaute",
  thief: "Roubo",
  "sucker-punch": "Soco Traiçoeiro",
  "dark-pulse": "Pulso Sombrio",
  "night-slash": "Corte Noturno",
  "foul-play": "Jogo Sujo",
  taunt: "Provocar",
  torment: "Tormento",
  snarl: "Resmungo",
  "nasty-plot": "Trama Maldosa",
  "throat-chop": "Golpe na Garganta",
  "beat-up": "Surra Coletiva",
  payback: "Troco",
  assurance: "Garantia",

  // ----- Steel -----
  "metal-claw": "Garra de Metal",
  "iron-tail": "Cauda de Ferro",
  "steel-wing": "Asa de Aço",
  "flash-cannon": "Canhão de Luz",
  "iron-head": "Cabeça de Ferro",
  "meteor-mash": "Pancada Meteoro",
  "bullet-punch": "Soco-Bala",
  autotomize: "Aliviar Peso",
  "iron-defense": "Defesa de Ferro",
  "metal-sound": "Som Metálico",
  "magnet-bomb": "Bomba Magnética",
  "gyro-ball": "Bola Giroscópica",
  "heavy-slam": "Pancada Pesada",
  "smart-strike": "Golpe Certeiro",
  "mirror-shot": "Tiro Espelhado",

  // ----- Fairy -----
  "fairy-wind": "Vento das Fadas",
  "dazzling-gleam": "Brilho Deslumbrante",
  moonblast: "Explosão Lunar",
  "draining-kiss": "Beijo Sugador",
  "disarming-voice": "Voz Desarmante",
  "play-rough-": "Brincadeira Bruta",
  charm: "Charme",
  "sweet-kiss": "Beijo Doce",
  "baby-doll-eyes": "Olhos de Boneca",
  "fairy-lock": "Trava das Fadas",
  "misty-terrain": "Terreno Enevoado",
  "moonlight": "Luar",
  "sweet-scent": "Aroma Doce",
  "aromatherapy": "Aromaterapia",
};

function fallbackLabel(name: string) {
  return name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

export function getMoveLabelPt(name: string): string {
  return MOVE_LABELS_PT[name] ?? fallbackLabel(name);
}
